# Configuración para trabajar con kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info.antenas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info.antenas
  template:
    metadata:
      labels:
        app: info.antenas
    spec:
      containers:
      - name: info-antenas-x9lsg
        image: info.antenas:1.0.0
        ports:
        - containerPort: 8080
        # Variables para cargar el application-dev.properties
        env:
        # Para agregar de forma automática el host:puerto de la instancia podemos hacerlo de la siguiente forma:
          - name: HOST_MAQUINA
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: HOST_PUERTO
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
         # FIN: Forma de agregar Host y puerto de forma automática
          - name: SPRING_DATASOURCE_URL
            # Para que cargue de forma directa se hace de está forma
            #value: "jdbc:sqlserver://host.docker.internal;encrypt=true;trustServerCertificate=true;databaseName=GestExp"
            # Si queremos que se cargue mediente el configmap.yml se hace de la siguiente forma:
            valueFrom:
              configMapKeyRef:
              # Le indicamos el metadata asociado al configmap.yml
                name: info.antenas.config.bbdd
                key: db_host
          - name: SPRING_DATASOURCE_USERNAME
            #value: "GestExp_User"
            valueFrom:
              #configMapKeyRef:
              # Cuando se utiliza datos sensibles lo más seguro es utilizar el secret.yml 
              # se debe indicar de la siguiente forma:
              secretKeyRef:
                name: info.antenas.config.bbdd
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            #value: "Joseplasencia11"
            valueFrom:
              secretKeyRef:
                name: info.antenas.config.bbdd
                key: password
          - name: show-sql
            valueFrom:
              configMapKeyRef:
                name: info.antenas.config.sql
                key: sho_sql
            #value: "true"
          - name: format_sql
            value: "true"
          - name: driver-class-name
            value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          - name: database-platform
            value: "org.hibernate.dialect.SQLServer2012Dialect"
          - name: logging.level
            value: "info"
          - name: hibernate.naming.physical-strategy
            value: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
          - name: PATH_LOGBACK
            value: file:/Users/joseplasenciavillarejo/Desktop/infoantenas_repository/logback-info.xml
        volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          hostPath:
          # Esto me va a crear una carpeta dentro de este repositorio, tengo que ver por que si existe,
          # no me utiliza la que ya tengo por defecto
            path: /Users/joseplasenciavillarejo/Desktop/infoantenas_repository
            type: Directory
          #persistentVolumeClaim:
          #claimName: infoantenas-pvc
          
        #- name: logs
        #  hostPath:
        #    path: /Users/joseplasenciavillarejo/Desktop/infoantenas_repository/logs
            
            
