apiVersion: apps/v1
kind: Deployment
metadata:
  name: info.antenas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info.antenas
  template:
    metadata:
      labels:
        app: info.antenas
    spec:
      containers:
      - image: info.antenas:1.0.0
        name: info-antenas-x9lsg
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:sqlserver://host.docker.internal;encrypt=true;trustServerCertificate=true;databaseName=GestExp"
          - name: SPRING_DATASOURCE_USERNAME
            value: "GestExp_User"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "Joseplasencia10"
          - name: show-sql
            value: "true"
          - name: format_sql
            value: "true"
          - name: driver-class-name
            value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          - name: database-platform
            value: "org.hibernate.dialect.SQLServer2012Dialect"
          - name: logging.level
            value: "info"
          - name: hibernate.naming.physical-strategy
            value: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
