# Configuración para trabajar con kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: info.antenas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: info.antenas
  template:
    metadata:
      labels:
        app: info.antenas
    spec:
      containers:
      - image: info.antenas:1.0.0
        name: info-antenas-x9lsg
        ports:
        - containerPort: 8080
        # Variables para cargar el application-dev.properties
        env:
          - name: SPRING_DATASOURCE_URL
            # Para que cargue de forma directa se hace de está forma
            #value: "jdbc:sqlserver://host.docker.internal;encrypt=true;trustServerCertificate=true;databaseName=GestExp"
            # Si queremos que se cargue mediente el configmap.yml se hace de la siguiente forma:
            valueFrom:
              configMapKeyRef:
              # Le indicamos el metadata asociado al configmap.yml
                name: info.antenas.config.bbdd
                key: db_host
          - name: SPRING_DATASOURCE_USERNAME
            #value: "GestExp_User"
            valueFrom:
              #configMapKeyRef:
              # Cuando se utiliza datos sensibles lo más seguro es utilizar el secret.yml 
              # se debe indicar de la siguiente forma:
              secretKeyRef:
                name: info.antenas.config.bbdd
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            #value: "Joseplasencia10"
            valueFrom:
              secretKeyRef:
                name: info.antenas.config.bbdd
                key: password
          - name: show-sql
            valueFrom:
              configMapKeyRef:
                name: info.antenas.config.sql
                key: sho_sql
            #value: "true"
          - name: format_sql
            value: "true"
          - name: driver-class-name
            value: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
          - name: database-platform
            value: "org.hibernate.dialect.SQLServer2012Dialect"
          - name: logging.level
            value: "info"
          - name: hibernate.naming.physical-strategy
            value: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
          - name: PATH_LOGBACK
            value: file:/Users/joseplasenciavillarejo/Desktop/infoantenas_repository/logback-info.xml
        volumeMounts:
            - name: logback-config
              mountPath: /Users/joseplasenciavillarejo/Desktop/infoantenas_repository
            #- name: logs
            #  mountPath: /config/logs
      volumes:
        - name: logback-config
          persistentVolumeClaim:
            claimName: infoantenas-pvc
           
          #hostPath:
          #  path: /Users/joseplasenciavillarejo/Desktop/infoantenas_repository
          #  type: DirectoryOrCreate
        #- name: logs
        #  hostPath:
        #    path: /Users/joseplasenciavillarejo/Desktop/infoantenas_repository/logs
            
            
